### ISSUE TITLE
Undertow Deprecated API is used 

### ISSUE THREAD

**Issue by mchoma** [wildfly-security/elytron-web#21]
I wonder if it is possible to avoid use of Undertow API marked as deprecated.

If I try to build
`[mchoma@localhost elytron-web]$ mvn test`

I get:

- [WARNING] /elytron-web/undertow/src/main/java/org/wildfly/elytron/web/undertow/server/SecurityContextImpl.java:[101,28] getIdentityManager() in io.undertow.security.api.SecurityContext has been deprecated
- [WARNING] /elytron-web/undertow/src/main/java/org/wildfly/elytron/web/undertow/server/SecurityContextImpl.java:[93,42] getAuthenticationMechanisms() in io.undertow.security.api.SecurityContext has been deprecated
- [WARNING] /elytron-web/undertow/src/main/java/org/wildfly/elytron/web/undertow/server/SecurityContextImpl.java:[85,17] addAuthenticationMechanism(io.undertow.security.api.AuthenticationMechanism) in io.undertow.security.api.SecurityContext has been deprecated
- [WARNING] /elytron-web/undertow/src/main/java/org/wildfly/elytron/web/undertow/server/SecurityContextImpl.java:[67,21] setResponseCode(int) in io.undertow.server.HttpServerExchange has been deprecated
- [WARNING] /elytron-web/undertow/src/test/java/org/wildfly/elytron/web/undertow/server/DefaultServer.java:[141,32] ENABLE_CONNECTOR_STATISTICS in io.undertow.UndertowOptions has been deprecated

**Comment by darranl** [comment]
In this case I believe the warning we see here is because we are implementing a class that contains deprecated methods.  For our integration the best we can do is add annotations to suppress the warnings.

Once Undertow moves back to being Java 8 in theory these methods could become default methods so they don't have to be implemented anymore by integrations that don't support them.

**Comment by mchoma** [comment]
Yes that is the case of first 3 warnings. 
In 4th case it will be probably safe to change from setResponseCode(int) to setStatusCode(int), which is called in setResponseCode anyway. 
In 5th case it will be probably safe to change from ENABLE_CONNECTOR_STATISTICS to ENABLE_STATISTICS, which is alias anyway.

I can send PR, if you like.

**Comment by darranl** [comment]
Sure PRs more than welcome, if we can get the clean up tasks out the way we can focus on the more serious issues that may pop up.
