### ISSUE TITLE
OutOfMemoryError in TS

### ISSUE THREAD

**Issue by mchoma** [wildfly-security/elytron-web#39]
@pedroigor , commit [1] introduced occurence of OutOfMemoryError. Could you have a look, what could be a problem, please? For example On IBM java ClientCertAuthenticationTest could not be run until -Xmx1024 is configured in surefire plugin.

Is just setting enough of memory (let say -Xmx1024) proper solution here? And high memory consumption is just caused by 2 Undertow server started inside TS. 

Or could be code somehow optimized? Could you review if committed changes are all right?

[1] https://github.com/wildfly-security/elytron-web/commit/21e224173c062170f182fcb588b87d4803624143

**Comment by mchoma** [comment]
@pedroigor , any thoughts?

**Comment by pedroigor** [comment]
@mchoma, can you try to run tests again ?

I was able to reproduce the OOM. You should be able now to run with just ```-Xmx64m -Xms64m```. Maybe less ?

**Comment by mchoma** [comment]
https://github.com/wildfly-security/elytron-web/pull/42 fix this
