### ISSUE TITLE
Enable SSO and Clustered Tests

### ISSUE THREAD

**Issue by darranl** [wildfly-security/elytron-web#45]
[org.wildfly.elytron.web.undertow.server.FormAuthenticationWithSessionReplicationTest-output.txt](https://github.com/wildfly-security/elytron-web/files/631124/org.wildfly.elytron.web.undertow.server.FormAuthenticationWithSessionReplicationTest-output.txt)
[org.wildfly.elytron.web.undertow.server.FormAuthenticationWithSessionReplicationTest.txt](https://github.com/wildfly-security/elytron-web/files/631125/org.wildfly.elytron.web.undertow.server.FormAuthenticationWithSessionReplicationTest.txt)

[org.wildfly.elytron.web.undertow.server.FormAuthenticationWithClusteredSSOTest-output.txt](https://github.com/wildfly-security/elytron-web/files/631126/org.wildfly.elytron.web.undertow.server.FormAuthenticationWithClusteredSSOTest-output.txt)
[org.wildfly.elytron.web.undertow.server.FormAuthenticationWithClusteredSSOTest.txt](https://github.com/wildfly-security/elytron-web/files/631127/org.wildfly.elytron.web.undertow.server.FormAuthenticationWithClusteredSSOTest.txt)

**Comment by pedroigor** [comment]
@darranl,  it looks like the cluster is not being formed during your tests. That is probably the cause. 

The main configuration to make get it working is -Djava.net.preferIPv4Stack=true, which is configured for ```maven-surefire-plugin```. Can you please provide maven debug output ?

**Comment by mchoma** [comment]
@pedroigor , any thoughts?
