### ISSUE TITLE
TS: ELY06012: Invalid logout message received for local session

### ISSUE THREAD

**Issue by mchoma** [wildfly-security/elytron-web#59]
During testsuite run
`mvn clean test -Dmaven.test.redirectTestOutputToFile=false`

there occures a lot of error messages: 
`ELY06013: Failed to invalidate local session: java.lang.IllegalStateException: ELY06012: Invalid logout message received for local session [MGgAaDPABGTDlU343a1FE8ophkLtEB8r7Gz16bPI]`

@pferraro ^^

**Comment by pferraro** [comment]
@mchoma ok - I see the problem.  It's just an issue with the test.  Will send an fix asap.

**Comment by pferraro** [comment]
@mchoma Fix is here: https://github.com/wildfly-security/elytron-web/pull/61
